-- AlterTable
ALTER TABLE "Team" ADD COLUMN     "drawsCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "losesCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "winsCount" INTEGER NOT NULL DEFAULT 0;
